"""empty message

Revision ID: 2cf039d7a733
Revises: 64b0bf46d9a8
Create Date: 2024-11-23 20:17:51.960462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf039d7a733'
down_revision = '64b0bf46d9a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_column('game_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.VARCHAR(length=120), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
