"""empty message

Revision ID: 647a2076dd3c
Revises: aeb663800a62
Create Date: 2024-11-19 18:13:17.329896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647a2076dd3c'
down_revision = 'aeb663800a62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
